package templates

const HtmlTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SPM-Go Results</title>
    <style>
        body, html {
            margin:0; padding: 0;
            height: 100%;
        }
        body {
			padding: 10px;
            font-family: Helvetica Neue, Helvetica, Arial;
            font-size: 14px;
            color:#333;
        }
        .analysis-summary {
            border-collapse: collapse;
            width: 100%;
        }
        .analysis-summary tr { border-bottom: 1px solid #bbb; }
        .analysis-summary td, .analysis-summary th { padding: 10px; }
        .analysis-summary tbody { border: 1px solid #bbb; }
        .analysis-summary td { border-right: 1px solid #bbb; background: #fff4c2; }
        .analysis-summary td:last-child { border-right: none; }
        .analysis-summary th {
            border: 1px solid #bbb;
            text-align: center;
            font-weight: bold;
            white-space: nowrap;
        }
        .analysis-summary tfoot td { }
        .green > td { background: rgb(230,245,208) !important; }
        .red > td { background: #FCE1E5 !important; }
        .bold { font-weight: bold; }
        .right { text-align: right; }
        .right-spaced { padding-right: 40px !important; }
		.footer {
			color: rgba(0,0,0,0.5);
			text-align: center;
			margin-top: 10px;
			height: 50px;
		}
    </style>
</head>
<body>
<h1>Software Package Metrics for Go - v{{.Version}}</h1>
<h2>Results for Module: {{.Module}}</h2>
<h2>Packages Analysis</h2>
<div class="results">
<table class="analysis-summary">
    <thead>
    <tr>
        <th style="width:120px;" rowspan="2">Name</th>
        <th rowspan="2">Package Path</th>
        <th rowspan="2" style="width:60px;">Files</th>
        <th colspan="3">Instability</th>
        <th colspan="3">Abstractness</th>
        <th colspan="3">Distance</th>
    </tr>
    <tr>
        <th style="width:120px;">C<sub>Afferent</sub></th>
        <th style="width:120px;">C<sub>Efferent</sub></th>
        <th style="width:120px;">Instability</th>
        <th style="width:120px;">N<sub>Abstractions</sub></th>
        <th style="width:120px;">N<sub>Implementations</sub></th>
        <th style="width:120px;">Abstractness</th>
        <th style="width:120px;">Distance</th>
    </tr>
    </thead>
    <tbody>
    {{ range .Packages }}
    <tr class="{{if le .Distance 0.1}}green{{else if gt .Distance 0.6}}red{{end}}">
        <td class="">{{ .Name }}</td>
        <td class="">{{ .Path }}</td>
        <td class="right">{{ .FilesCount }}</td>
        <td class="right right-spaced">{{ .AfferentCoupling }}</td>
        <td class="right right-spaced">{{ .EfferentCoupling }}</td>
        <td class="bold right right-spaced">{{ .Instability }}</td>
        <td class="right right-spaced">{{ .AbstractionsCount }}</td>
        <td class="right right-spaced">{{ .ImplementationsCount }}</td>
        <td class="bold right right-spaced">{{ .Abstractness }}</td>
        <td class="bold right right-spaced">{{ .Distance }}</td>
    </tr>
    {{ end }}
    </tbody>
</table>
</div>
<div class="footer">
	Report generated by
	<a href="https://pkg.go.dev/github.com/fdaines/spm-go" target="_blank">SPM-Go</a>
	at {{.TimeStamp}}
</div>
</body>
</html>`